### ISSUE TITLE
Apparent issue with 'morpheus network-groups update # --group-access #,#,#,# command

### ISSUE THREAD

**Issue by rjr162** [gomorpheus/morpheus-cli#7]
If I run the 'networks update 1 --group-access 1,2' sort of command, permissions are set properly

if I run 'network-groups update 1 --group-access 1,2' sort of command, all I get back is "* data: No data provided"

**Comment by jamesdickson6** [comment]
This will be fixed in 4.2.10, coming out next week (ish)

**Comment by jamesdickson6** [comment]
@rjr162 There is a workaround until the next cli is published.
The method is rather silly, but it works. The API is erroring because the payload has an empty networkGroup payload.  You can work around this by specifying any property, even it does nothing. eg. `network-groups update 1 --group-access 1,2 -O foo=bar`

**Comment by rjr162** [comment]
Thank you sir! I looked at trying to assist with a patch but quickly realized I wasn't sure where to start

**Comment by jamesdickson6** [comment]
This is fixed in the 4.2.1 appliance. In the meantime, the CLI has the afformentioned workaround
